import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const funnelDisplay = localFont({
  src: './fonts/FunnelDisplay-Regular.ttf',
  variable: '--font-funnel-display',
  display: 'swap',
});

const monaSans = localFont({
  src: "./fonts/MonaSans-Regular.ttf",
  variable: "--font-mona-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PalmBloc",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${funnelDisplay.variable} ${monaSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
